version: '2'
services:
 zookeeper:
   image: 'confluentinc/cp-zookeeper:latest'
   container_name: zookeeper
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
   ports:
     - '2181:2181'
 kafka:
   image: 'confluentinc/cp-kafka:latest'
   container_name: kafka
   depends_on:
     - zookeeper
   ports:
     - '9092:9092'
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
 schema-registry:
   image: confluentinc/cp-schema-registry:4.1.1
   hostname: schema-registry
   ports:
   - "38081:38081"
   depends_on:
   - kafka
   environment:
     SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
     SCHEMA_REGISTRY_HOST_NAME: schema-registry
     SCHEMA_REGISTRY_LISTENERS: http://schema-registry:38081
     SCHEMA_REGISTRY_DEBUG: "true"

 kafka-rest:
   image: confluentinc/cp-kafka-rest:4.1.1
   hostname: kafka-rest
   ports:
   - "38082:38082"
   depends_on:
     - schema-registry
   environment:
     KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_REST_SCHEMA_REGISTRY_URL: schema-registry:38081
     KAFKA_REST_HOST_NAME: kafka-rest
     KAFKA_REST_LISTENERS: http://kafka-rest:38082
 postgres:
   image: postgres:10-bullseye
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - 5432:5432
 redis:
   image: redis:3.2
   ports:
     - 6379:6379
